name: "New Camera Entry Alt"
description: "Add information about a new camera to this project"
title: "[New Camera Entry]"
labels: documentation
assignees: 
  - rowskilled14
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing to this project!
        ### Please provide as much detail as possible as you fill out this form so that the camera entry is as complete as possible.
# Brand
  - type: input
    id: brand
    attributes: 
      label: "Brand of Device:"
      # description: "What brand is your device?  
      placeholder: "eg. Dahua, Hikvision, Axis, Uniview, Reolink, etc"
    validations:
      required: true
# Category
  - type: input
    id: category
    attributes: 
      label: "Category of Device:"
      # description:
      placeholder: "eg. PoE; Wi-Fi; BNC; etc"
    validations:
      required: true
# Model
  - type: input
    id: model
    attributes: 
      label: "Model of Device:"
      # description:
      placeholder: "eg. IPC-HDW5442TM-ASE-S3, IPC-HDW5849H-ASE-LED, etc"
    validations:
      required: true
# Description
  - type: textarea
    id: description
    attributes: 
      label: "Short Description of Product:"
      description: "Please provide a short description of the product.  Keep it free of bias as much as possible, but describe the use case and make note of important/defining qualities."
      placeholder: "eg. The Dahua Color-4k-T camera series offers a large resolution without compromising on sensor and aperture sizing.  With an 8MP, 1/1.2 inch sensor and F1.0 aperture, this camera offers excellent low light performance.  White lights are available on the device, but IR is not present or supported.  A little ambient white light will be required for a product like this.  With proper settings, smooth motion can still be captured without ghosting, smearing, artifacting, etc even in very low light conditions."
    validations:
      required: false
# Price
  - type: input
    id: price
    attributes: 
      label: "Typical Price"
      description: "List a typical price for the camera."
      placeholder: "eg. $120-140"
    validations:
      required: true
# # Price
#   - type: input
#     id: price
#     attributes: 
#       label: "Typical Price"
#       description: "List a typical price for the camera."
#       placeholder: "eg. $120-140"
#     validations:
#       required: true
# Features
  - type: textarea
    id: features
    attributes: 
      label: "Features"
      description: "Make a bulleted list of features.  Start each line with an asterisk: `*` and put one feature per bullet point / line.  Be as comprehensive as possible, listing all features you can."
      placeholder: |
        * ONVIF Compliant 2 way audio
        * White LED lights 
        * IR LED Lights 
        * Variable Zoom
        * PTZ
        * AI Detection features
        * As much detail as possible per each
    validations:
      required: true
# Camera Stream Endpoints/URLs
  - type: textarea
    id: endpoints
    attributes: 
      label: "Known Camera Stream API Endpoints/URIs"
      description: "Make a bulleted list of all endpoints.  Start each line with an asterisk: `*` and put one feature per bullet point / line.  Be as comprehensive as possible, listing all endpoints you can.  Use a standard format, putting placeholders for user customized parts of the URI.  Add notes whenever necessary."
      placeholder: |
        * rtsp://{username}:{password}@{ip_address}:554/cam/realmonitor?channel=1&subtype=0
        * rtsp://{username}:{password}@{ip_address}:554/cam/realmonitor?channel=1&subtype=2
          * Port can be customized in options but will always default to 554
    validations:
      required: true
# Example Config
  - type: textarea
    id: config
    attributes: 
      label: "Example config - primarily targeting go2rtc and Frigate"
      description: "Add the config used in your NVR setup, preferably Frigate and/or go2rtc.  Include anything relevant to the camera, but omit irrelevant NVR information."
      placeholder: |
        Go2rtc Example:
          streams: 
            cam1:
              - rtsp://{username}:{password}@{ip_address}:554/cam/realmonitor?channel=1&subtype=0
              - ffmpeg:cam1#audio=opus#audio=copy
        Frigate Example:
          streams: 
            cam1:
              - rtsp://{username}:{password}@{ip_address}:554/cam/realmonitor?channel=1&subtype=0
              - ffmpeg:cam1#audio=opus#audio=copy
          cameras:
            Livingroom:
              ffmpeg:
                inputs:
                  - path: rtsp://127.0.0.1:8554/cam1
                    roles:
                      - record
                      - detect
              record:
                enabled: true
              live:
                stream_name: cam1
              objects:
                track:
                  - person
                  - cat
                  - bird
                  - dog
              motion:
                mask: coods
    validations:
      required: true
# Description of config
  - type: textarea
    id: config_description
    attributes: 
      label: "Config description"
      description: "Add a description for the above configuration.  Apply any necessary information."
      placeholder: "The above description shows this camera being used in Frigate.  It should be noted that ..."
    validations:
      required: false
# Alternate config and description
  - type: textarea
    id: altconfig
    attributes: 
      label: "Alternate Example config - primarily targeting go2rtc and Frigate"
      description: "Alternate config to above.  If multiple configs are relevant, add second config details here.  Add the config used in your NVR setup, preferably Frigate and/or go2rtc.  Include anything relevant to the camera, but omit irrelevant NVR information."
      placeholder: |
        Go2rtc Example:
          streams: 
            cam1:
              - rtsp://{username}:{password}@{ip_address}:554/cam/realmonitor?channel=1&subtype=0
              - ffmpeg:cam1#audio=opus#audio=copy
        Frigate Example:
          streams: 
            cam1:
              - rtsp://{username}:{password}@{ip_address}:554/cam/realmonitor?channel=1&subtype=0
              - ffmpeg:cam1#audio=opus#audio=copy
          cameras:
            Livingroom:
              ffmpeg:
                inputs:
                  - path: rtsp://127.0.0.1:8554/cam1
                    roles:
                      - record
                      - detect
              record:
                enabled: true
              live:
                stream_name: cam1
              objects:
                track:
                  - person
                  - cat
                  - bird
                  - dog
              motion:
                mask: coods
    validations:
      required: false
# Description of alternate config
  - type: textarea
    id: altconfig_description
    attributes: 
      label: "Alternate Config description"
      description: "Add a description for the above configuration.  Apply any necessary information."
      placeholder: "The above description shows this camera being used in Frigate.  It should be noted that ..."
    validations:
      required: false
# Known issues / limitations
  - type: textarea
    id: known_issues
    attributes: 
      label: "Known issues / limitations"
      description: "Describe any known limitations, shortcomings, problems, or issues with the camera here.  Add issues even if they were mentioned in a prior field.  Include workarounds if applicable."
      placeholder: "It is a known issue that this camera cannot support the X feature on firmware versions...  ...A workaround exists via...  ...The camera isn't compatible with..."
    validations:
      required: false
# Known compatibility with tools: 
  - type: textarea
    id: known_compatibility
    attributes: 
      label: "Known Compatibility with"
      description: "Make a bulleted list of any tools, projects, applications, etc that you know the camera is compatible with.  Start each line with an asterisk: `*` and put one feature per bullet point / line.  Be as comprehensive as possible, listing all entities you can.  Add notes whenever necessary."
      placeholder: |
        * Frigate
        * go2rtc
        * Shinobi
    validations:
      required: false
# Tested firmware
  - type: textarea
    id: firmware
    attributes: 
      label: "Tested firmware version(s)"
      description: "Make a bulleted list of firmwares tested for this camera.  Start each line with an asterisk: `*` and put one feature per bullet point / line.  Be as comprehensive as possible, listing all entities you can.  Add notes whenever necessary."
      placeholder: |
        * 1.0.2
        * 2.0.1
        * 1.2.3
    validations:
      required: true
# Additional Information
  - type: textarea
    id: additional_info
    attributes: 
      label: "Additional Information / Notes"
      description: "Add any additional information which you would like to contribute, but which doesn't fit above here."
      placeholder: "Anything you'd like, within reason and relevance."
    validations:
      required: false
